// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Puroguramu.Infrastructures.Data;

#nullable disable

namespace Puroguramu.Infrastructures.Migrations
{
    [DbContext(typeof(PuroguramuDbContext))]
    partial class PuroguramuDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "01-04-24 10:30:00AdminId",
                            ConcurrencyStamp = "01-04-24 10:30:00AdminId",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "01-04-24 10:30:00TeacherId",
                            ConcurrencyStamp = "01-04-24 10:30:00TeacherId",
                            Name = "Teacher",
                            NormalizedName = "TEACHER"
                        },
                        new
                        {
                            Id = "01-04-24 10:30:00StudentId",
                            ConcurrencyStamp = "01-04-24 10:30:00StudentId",
                            Name = "Student",
                            NormalizedName = "STUDENT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "A000001",
                            RoleId = "01-04-24 10:30:00AdminId"
                        },
                        new
                        {
                            UserId = "A000002",
                            RoleId = "01-04-24 10:30:00TeacherId"
                        },
                        new
                        {
                            UserId = "A000003",
                            RoleId = "01-04-24 10:30:00StudentId"
                        },
                        new
                        {
                            UserId = "A000004",
                            RoleId = "01-04-24 10:30:00StudentId"
                        },
                        new
                        {
                            UserId = "T000001",
                            RoleId = "01-04-24 10:30:00TeacherId"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Puroguramu.Infrastructures.Data.Entities.Exercise", b =>
                {
                    b.Property<Guid>("IdExercise")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Publish")
                        .HasColumnType("bit");

                    b.Property<string>("Solution")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("States")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdExercise");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            IdExercise = new Guid("89a9b82b-6961-4d00-95a1-7ac8412598c2"),
                            Difficulty = "Medium",
                            Model = "// code-insertion-point\r\n\r\n            public class Test\r\n            {\r\n                public static TestResult Ensure(float b, int exponent, float expected)\r\n                {\r\n                  TestStatus status = TestStatus.Passed;\r\n                  float actual = float.NaN;\r\n                  try\r\n                  {\r\n                     actual = Exercice.Power(b, exponent);\r\n                     if(Math.Abs(actual - expected) > 0.00001f)\r\n                     {\r\n                         status = TestStatus.Failed;\r\n                     }\r\n                  }\r\n                  catch(Exception ex)\r\n                  {\r\n                     status = TestStatus.Inconclusive;\r\n                  }\r\n\r\n                  return new TestResult(\r\n                    string.Format(\"Power of {0} by {1} should be {2}\", b, exponent, expected),\r\n                    status,\r\n                    status == TestStatus.Passed ? string.Empty : string.Format(\"Expected {0}. Got {1}.\", expected, actual)\r\n                  );\r\n                }\r\n            }\r\n\r\n            return new TestResult[] {\r\n              Test.Ensure(2, 4, 16.0f),\r\n              Test.Ensure(2, -4, 1.0f/16.0f)\r\n            };\r\n            ",
                            Name = "Exercice 1",
                            Publish = true,
                            Solution = "Solution",
                            States = "Explication"
                        },
                        new
                        {
                            IdExercise = new Guid("9d14ac8c-6776-4da3-aeed-2332588b9d31"),
                            Difficulty = "Easy",
                            Model = "Model n'existe pas",
                            Name = "Exercice 2",
                            Publish = true,
                            Solution = "Solution",
                            States = "Explication"
                        },
                        new
                        {
                            IdExercise = new Guid("9aac602c-f7e2-475e-8eeb-9be12c3c2536"),
                            Difficulty = "Difficult",
                            Model = "Model n'existe pas",
                            Name = "Exercice 3",
                            Publish = true,
                            Solution = "Solution",
                            States = "Explication"
                        });
                });

            modelBuilder.Entity("Puroguramu.Infrastructures.Data.Entities.ExerciseUser", b =>
                {
                    b.Property<Guid>("IdExercise")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IdUser")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("bit");

                    b.Property<string>("Solution")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdExercise", "IdUser");

                    b.ToTable("ExercisesUsers");
                });

            modelBuilder.Entity("Puroguramu.Infrastructures.Data.Entities.IdentityPuroguramuUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Matricule")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<byte[]>("ProfilePicture")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "A000001",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "dc01b8e9-0d15-43aa-94fa-6ae2345c5528",
                            Email = "justin.fransolet@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Justin",
                            Group = "2i1",
                            LastName = "Fransolet",
                            LockoutEnabled = false,
                            Matricule = "A000001",
                            NormalizedUserName = "JUSTIN.FRANSOLET@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEGQV36zm6YB594B8ooNp3ak9yuP5cx9H3z5+VIA4T5szkoH4Wi2Ejd1oUtL9ce2B+A==",
                            PhoneNumberConfirmed = false,
                            ProfilePicture = new byte[0],
                            SecurityStamp = "6165bea8-a6d3-4440-99b6-35272ce0ddca",
                            TwoFactorEnabled = false,
                            UserName = "justin.fransolet@gmail.com"
                        },
                        new
                        {
                            Id = "A000002",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f7fdf403-f4ee-424f-8817-bdeed360785b",
                            Email = "clement.lemlijn@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Clement",
                            Group = "2i1",
                            LastName = "Lemlijn",
                            LockoutEnabled = false,
                            Matricule = "A000002",
                            NormalizedUserName = "CLEMENT.LEMLIJN@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEHJezVaCNVVWKXR+Vo9TcpfsKA0CzS8B+R57VlF8hUIaijX+1PA5T9LhlmTNgLIWwA==",
                            PhoneNumberConfirmed = false,
                            ProfilePicture = new byte[0],
                            SecurityStamp = "4865e2e6-6054-4041-b8e7-2425fca031ef",
                            TwoFactorEnabled = false,
                            UserName = "clement.lemlijn@gmail.com"
                        },
                        new
                        {
                            Id = "A000003",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "31fda27d-a24a-4ffc-be17-8ecfd748c283",
                            Email = "user.un@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "User1",
                            Group = "2i1",
                            LastName = "Un",
                            LockoutEnabled = false,
                            Matricule = "A000003",
                            NormalizedUserName = "USER.UN@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEMYG2ASkd1mscplrP6YrgNgrGrabmhNpGeQ7qR0lNjqRJMgPM/D1NLD5X2KDQOVsiw==",
                            PhoneNumberConfirmed = false,
                            ProfilePicture = new byte[0],
                            SecurityStamp = "1dbb64ba-578d-40dd-94b4-1709e27789e6",
                            TwoFactorEnabled = false,
                            UserName = "user.un@gmail.com"
                        },
                        new
                        {
                            Id = "A000004",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d1ecb401-3a59-41df-ba7d-0673c65d06cc",
                            Email = "user.deux@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "User2",
                            Group = "2i1",
                            LastName = "Deux",
                            LockoutEnabled = false,
                            Matricule = "A000004",
                            NormalizedUserName = "USER.DEUX@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEPR5DP9kvz+i96wzipaZcP6yubAdhdshZvN0Hcdjn3iczqhqnQND/AYIhWbUirgIUw==",
                            PhoneNumberConfirmed = false,
                            ProfilePicture = new byte[0],
                            SecurityStamp = "9052189a-385d-41a9-9ea8-5e5856db0c12",
                            TwoFactorEnabled = false,
                            UserName = "user.deux@gmail.com"
                        },
                        new
                        {
                            Id = "T000001",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "074f29df-dff7-41ce-9dd9-e163c8b3209d",
                            Email = "mr.teacher@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Teacher",
                            Group = "2i1",
                            LastName = "Mr",
                            LockoutEnabled = false,
                            Matricule = "T000001",
                            NormalizedUserName = "MR.TEACHER@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEOwMAS0+/PkumGzujxq830xXnqzxw4TByBhEJqEZmYzjA/qJR2ffVExAdLis84Mg/Q==",
                            PhoneNumberConfirmed = false,
                            ProfilePicture = new byte[0],
                            SecurityStamp = "e678c994-3020-4de1-b14b-8ca215d0d4a1",
                            TwoFactorEnabled = false,
                            UserName = "mr.teacher@gmail.com"
                        });
                });

            modelBuilder.Entity("Puroguramu.Infrastructures.Data.Entities.Lesson", b =>
                {
                    b.Property<Guid>("IdLesson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Publish")
                        .HasColumnType("bit");

                    b.HasKey("IdLesson");

                    b.ToTable("Lessons");

                    b.HasData(
                        new
                        {
                            IdLesson = new Guid("dfd5b0a5-40b3-41ec-8c0c-a44b8f0298f8"),
                            Description = "Description",
                            Name = "Leçon 1",
                            Publish = true
                        });
                });

            modelBuilder.Entity("Puroguramu.Infrastructures.Data.Entities.LessonExercise", b =>
                {
                    b.Property<Guid>("IdLesson")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdExercise")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.HasKey("IdLesson", "IdExercise");

                    b.ToTable("LessonsExercises");

                    b.HasData(
                        new
                        {
                            IdLesson = new Guid("dfd5b0a5-40b3-41ec-8c0c-a44b8f0298f8"),
                            IdExercise = new Guid("89a9b82b-6961-4d00-95a1-7ac8412598c2"),
                            Position = 0
                        },
                        new
                        {
                            IdLesson = new Guid("dfd5b0a5-40b3-41ec-8c0c-a44b8f0298f8"),
                            IdExercise = new Guid("9d14ac8c-6776-4da3-aeed-2332588b9d31"),
                            Position = 1
                        },
                        new
                        {
                            IdLesson = new Guid("dfd5b0a5-40b3-41ec-8c0c-a44b8f0298f8"),
                            IdExercise = new Guid("9aac602c-f7e2-475e-8eeb-9be12c3c2536"),
                            Position = 2
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Puroguramu.Infrastructures.Data.Entities.IdentityPuroguramuUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Puroguramu.Infrastructures.Data.Entities.IdentityPuroguramuUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Puroguramu.Infrastructures.Data.Entities.IdentityPuroguramuUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Puroguramu.Infrastructures.Data.Entities.IdentityPuroguramuUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
